### ISSUE TITLE
get od_id pairs that has no ring assigned in ring table

### ISSUE THREAD

**Issue by mk45** [mk45/pankus#12]
(1,4) has no ring assigned means that 4 is in no ring for 1

**Comment by wzelazo** [comment]
Probably done in commit https://github.com/mk45/pankus/commit/3ec4973a285c1c42ff1c3dd1a380a62aacb8ca5d
Waiting for the review

**Comment by wzelazo** [comment]
done in https://github.com/mk45/pankus/commit/6bb46c0b99036625432603c7f7748a3dd1738c78
