### ISSUE TITLE
Documentation of how to create documentation

### ISSUE THREAD

**Issue by mk45** [mk45/pankus#2]
As We probably use pydoc for documentation generation wee need:

- Mark(up/down) language support
- Table description and support for description string
- Review documentation by the end user ()

Modify Readme.md and create additional Project-wide information 

- How to generate documentation 
- How to install
- Example code

**Comment by wzelazo** [comment]
Pydoc turned out to be inefficient tool in our hands therefore we're going back to Sphinx

**Comment by wzelazo** [comment]
As we use github wiki for documentation, there is no need to create specific instructions how to add new content to the documentation
