### ISSUE TITLE
definition of activity (basic terminology)

### ISSUE THREAD

**Issue by maggal** [mk45/pankus#4]
https://github.com/mk45/taurus/wiki/Basic-terminology
On this page a definition of activity is as:
_Activity is a single pair of source and destination and its character_
Probably this definition describes 
INTERACTION (SPATIAL INTERACTION)

If we change the Activity into Interaction (Spatial interaction) - will it make a trouble with a code?

**Comment by wzelazo** [comment]
Since term "activity" was not used in the code itself its definition could be changed without causing more issues
