### ISSUE TITLE
show selectivity after create_escape_fraction_selectivity()

### ISSUE THREAD

**Issue by mk45** [mk45/pankus#9]

**Comment by mk45** [comment]
Done in commi a3e6d6b9c295b98d7e56ff8ab63f8b7457700613

**Comment by mk45** [comment]
Done in commit a3e6d6b9c295b98d7e56ff8ab63f8b7457700613

**Comment by mk45** [comment]
@wzelazo Can You please update documentation if needed

**Comment by wzelazo** [comment]
Done in commit "issue #8 & #9 resolved"
